/**
 * IFS (Iterated Function System) types.
 *
 * An IFS fractal is defined by a set of affine transformations applied
 * probabilistically via the "chaos game" algorithm. Each transform maps
 * a point (x, y) to:
 *   x' = a*x + b*y + e
 *   y' = c*x + d*y + f
 */

/** A single affine transformation with probability weight */
export interface IFSTransform {
  /** Affine coefficient a (x scale / rotation) */
  a: number;
  /** Affine coefficient b (x shear) */
  b: number;
  /** Affine coefficient c (y shear) */
  c: number;
  /** Affine coefficient d (y scale / rotation) */
  d: number;
  /** Translation x */
  e: number;
  /** Translation y */
  f: number;
  /** Probability weight (will be normalized) */
  p: number;
  /** Optional display color (hex) for this transform */
  color?: string;
}

/** A point generated by the IFS chaos game */
export interface IFSPoint {
  x: number;
  y: number;
  /** Which transform generated this point (index into transforms array) */
  transformIndex: number;
}

/** An IFS fractal preset */
export interface IFSPreset {
  name: string;
  description: string;
  transforms: IFSTransform[];
  /** Recommended default point count */
  defaultPoints: number;
  /** Default colors for each transform */
  colors?: string[];
}

/** IFS-specific parameters within FractalParams */
export interface IFSParams {
  /** Active IFS preset key */
  ifsPreset: string;
  /** Number of points to generate */
  ifsPoints: number;
  /** Custom IFS mode */
  ifsCustomMode: boolean;
  /** Custom transforms as JSON string */
  ifsCustomTransforms: string;
}
