"use client";

import { useCallback } from "react";
import { Slider, LabelWithTooltip } from "./Slider";
import { IFS_PRESETS, IFS_PRESET_ORDER } from "@/lib/presets/ifs-presets";
import type { FractalParams } from "@/lib/engine/types";

interface IFSControlPanelProps {
  params: FractalParams;
  onParamChange: (key: keyof FractalParams, value: number | string | boolean | string[]) => void;
  onIFSPresetChange: (presetKey: string) => void;
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="px-4 py-4 border-b border-border-subtle">
      <h3 className="text-[10px] font-semibold uppercase tracking-[0.15em] text-text-tertiary mb-3 font-[family-name:var(--font-display)]">
        {title}
      </h3>
      <div className="flex flex-col gap-4">{children}</div>
    </div>
  );
}

export function IFSControlPanel({
  params,
  onParamChange,
  onIFSPresetChange,
}: IFSControlPanelProps) {
  const currentPreset = IFS_PRESETS[params.ifsPreset];

  const handlePoints = useCallback(
    (v: number) => onParamChange("ifsPoints", v),
    [onParamChange]
  );
  const handleScale = useCallback(
    (v: number) => onParamChange("scale", v),
    [onParamChange]
  );
  const handleRotation = useCallback(
    (v: number) => onParamChange("rotation", v),
    [onParamChange]
  );

  return (
    <div className="flex flex-col">
      {/* IFS Preset selector */}
      <Section title="IFS Preset">
        <div className="grid grid-cols-2 gap-1.5">
          {IFS_PRESET_ORDER.map((key) => {
            const preset = IFS_PRESETS[key];
            const isActive = params.ifsPreset === key && !params.ifsCustomMode;
            return (
              <button
                key={key}
                onClick={() => {
                  onParamChange("ifsCustomMode", false);
                  onIFSPresetChange(key);
                }}
                className={`
                  px-2.5 py-2 rounded-md text-[11px] font-[family-name:var(--font-display)] font-medium
                  text-left transition-all duration-150
                  ${
                    isActive
                      ? "bg-accent/12 text-accent border border-accent/25 shadow-[0_0_12px_rgba(91,245,160,0.06)]"
                      : "bg-bg-tertiary/50 text-text-secondary border border-transparent hover:bg-bg-tertiary hover:text-text-primary"
                  }
                `}
                title={preset.description}
              >
                {preset.name}
              </button>
            );
          })}
        </div>
      </Section>

      {/* Generation controls */}
      <Section title="Generation">
        <Slider
          label="Points"
          tooltip="Number of points generated by the chaos game. More points = sharper detail and denser rendering, but slower generation."
          value={params.ifsPoints}
          min={1000}
          max={500000}
          step={1000}
          onChange={handlePoints}
          decimals={0}
        />
        <div className="flex items-center justify-between">
          <LabelWithTooltip label="Seed" tooltip="Controls the random number generator for point placement. Same seed = same pattern every time." />
          <div className="flex items-center gap-1.5">
            <span className="text-[11px] font-[family-name:var(--font-mono)] text-accent tabular-nums">
              {params.seed}
            </span>
            <button
              onClick={() => onParamChange("seed", Math.floor(Math.random() * 100000))}
              className="text-[9px] font-[family-name:var(--font-mono)] px-1.5 py-0.5 rounded bg-bg-tertiary/50 text-text-tertiary hover:text-text-primary border border-border-subtle transition-all"
              title="Randomize seed"
            >
              🎲
            </button>
          </div>
        </div>
      </Section>

      {/* Visual controls */}
      <Section title="Appearance">
        <Slider
          label="Scale"
          tooltip="Zoom level of the point cloud on the canvas. Values above 1× enlarge, below 1× shrink."
          value={params.scale}
          min={0.1}
          max={3.0}
          step={0.05}
          onChange={handleScale}
          unit="×"
        />
        <Slider
          label="Rotation"
          tooltip="Rotate the entire point cloud around its center."
          value={params.rotation}
          min={0}
          max={360}
          step={1}
          onChange={handleRotation}
          unit="°"
          decimals={0}
        />

        {/* Background controls */}
        <div className="flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <LabelWithTooltip label="Background" tooltip="Canvas and SVG export background. Transparent is best for Figma import." />
            <button
              onClick={() => onParamChange("bgTransparent", !params.bgTransparent)}
              className={`text-[9px] font-[family-name:var(--font-mono)] px-2 py-0.5 rounded border transition-all ${
                params.bgTransparent
                  ? "bg-bg-tertiary/50 text-text-tertiary border-border-subtle"
                  : "bg-accent/10 text-accent border-accent/25"
              }`}
            >
              {params.bgTransparent ? "transparent" : "solid"}
            </button>
          </div>
          {!params.bgTransparent && (
            <div className="flex items-center gap-2">
              <input
                type="color"
                value={params.bgColor}
                onChange={(e) => onParamChange("bgColor", e.target.value)}
                className="w-6 h-6 rounded cursor-pointer border border-border-subtle bg-transparent"
                title="Background color"
              />
              <span className="text-[10px] font-[family-name:var(--font-mono)] text-text-tertiary">
                {params.bgColor}
              </span>
            </div>
          )}
        </div>

        {/* Stroke color */}
        <div className="flex flex-col gap-2">
          <LabelWithTooltip label="Point Color" tooltip="Fallback color when the preset doesn't define per-transform colors. Most presets use their own color palette." />
          <div className="flex items-center gap-2">
            <input
              type="color"
              value={params.strokeColor}
              onChange={(e) => onParamChange("strokeColor", e.target.value)}
              className="w-6 h-6 rounded cursor-pointer border border-border-subtle bg-transparent"
              title="Point color (used when preset has no colors)"
            />
            <span className="text-[10px] font-[family-name:var(--font-mono)] text-text-tertiary">
              {params.strokeColor}
            </span>
          </div>
        </div>
      </Section>

      {/* Info panel */}
      <div className="px-4 py-4">
        <div className="bg-bg-tertiary/40 rounded-md p-3 border border-border-subtle">
          <p className="text-[10px] font-[family-name:var(--font-mono)] text-text-tertiary leading-relaxed">
            {currentPreset?.description ?? "Select an IFS preset"}
          </p>
          {currentPreset && (
            <div className="mt-2 text-[10px] font-[family-name:var(--font-mono)] text-text-tertiary">
              <span>
                {currentPreset.transforms.length} transforms
              </span>
              {/* Color swatches */}
              {currentPreset.colors && (
                <div className="flex gap-1 mt-1.5">
                  {currentPreset.colors.map((c, i) => (
                    <div
                      key={i}
                      className="w-4 h-4 rounded-sm border border-border-subtle"
                      style={{ backgroundColor: c }}
                      title={`Transform ${i}: ${c}`}
                    />
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
